### PR TITLE
LWMS ID 5307 for OCW - last updates

### PR DESCRIPTION
**Pull request by vltabacaru**
Thank you!

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issue with your PR:
In workshops/ocw-freetier/manifest.json and workshops/ocw-livelabs/manifest.json, replace the old raw GitHub links with the new oracle-livelabs.github.io links. See examples here: https://github.com/oracle-livelabs/common/blob/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/manifest.json.
Thanks!

**Comment by vltabacaru** [comment]
Done. Thank you!

**Comment by madhusudhanrao-ppm** [comment]
This branch has conflicts that must be resolved

mongo-api/workshops/ocw-livelabs/index.html
mongo-api/workshops/ocw-livelabs/manifest.json
mongo-api/workshops/ocw/index.html
mongo-api/workshops/ocw/manifest.json

**Comment by vltabacaru** [comment]
"Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Pull request closed without merging**
