### PR TITLE
WMSID: 11620 - PLSQL RAG Livelab #134

### PR DESCRIPTION
**Pull request by mw-orcl**
WMSID: 11620 - PLSQL RAG Livelab #134
Updated step to browse to the Home folder to select PDF files

### CODE REVIEW

**Comment by mw-orcl** [comment]
Please approve merge for spelling and grammar edits.

**Review by ramonamagadan18 — APPROVED** [review]

**Comment by ramonamagadan18** [comment]
Hi @mw-orcl! Please review _plsql-rag-23ai/lab1/lab1.md_ because it creates conflict

**Comment by mw-orcl** [comment]
Hi Ramona, I don't see the conflicts to resolve.

**Comment by mw-orcl** [comment]
Ramona, please review.  We resolved the conflicts.  Seams we have race condition with me and Rajeev updates.

**Review by ramonamagadan18 — APPROVED** [review]

**Pull request merged**
