### PR TITLE
WMS ID: 5307 - Changes to get content updated to OCW-April 2023

### PR DESCRIPTION
**Pull request by PriscilaIruela**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@PriscilaIruela - Please make these highlighted image file names lowercase and descriptive like adb-provision for example.

Also, move all the images to the images folder instead of having them in individual task folders
image

**Comment by PriscilaIruela** [comment]
Hi @anooshapilli , I have applied the changes. Thanks!

**Comment by ZRTalke** [comment]
Hi @PriscilaIruela 

Thanks for updating those image files. Can you please provide the WMS id for all the workshops altered? Then I should be able to approve your pull request

**Comment by PriscilaIruela** [comment]
WMS ID: 5307.

Best regards,
Priscila

**Comment by vltabacaru** [comment]
Hi all,
Apart from WMS ID: 5307, I made some minor updates to WMS ID 5299, and WMS ID 5302. Just very small fixes, they are in the same repository.
Thank you

**Comment by vltabacaru** [comment]
I'm not sure if those updates are related to your question, because they are in a different pull request:
 LWMS ID 5302 updates quarterly QA #84

**Comment by anooshapilli** [comment]
@PriscilaIruela - Could you confirm if the requested changes are made to the workshop?

**Comment by PriscilaIruela** [comment]
Hi @Anoosha ***@***.***>, I am actually on holidays! I will make the changes as soon as I have access to a computer.

Regards,
Priscila
________________________________
From: Anoosha Pilli ***@***.***>
Sent: Tuesday, April 25, 2023 2:53:40 AM
To: oracle-livelabs/pts ***@***.***>
Cc: Priscila Araceli Iruela Lasarte ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/pts] WMS ID: 5307 - Changes to get content updated to OCW-April 2023 (PR #83)


@PriscilaIruela<https://urldefense.com/v3/__https://github.com/PriscilaIruela__;!!ACWV5N9M2RV99hQ!PGFfx_-sp-uWnetn_IC9uXqRyCWPshleqtCTwJ7n1-FP9zG47SgC9M06yWwrO5ZskFdaJwrxGSCSW_0CgXc-oQFG5vQT$> - Could you confirm if the requested changes are made to the workshop?

**Comment by PriscilaIruela** [comment]
Hello @anooshapilli

The latest commit in this PR reverted the unwanted change files on other workshops. Now it should be good to proceed.

Thank you.

**Review by ramumg — APPROVED** [review]

**Pull request merged**
