### PR TITLE
WMS 11631

### PR DESCRIPTION
**Pull request by bhenndricks**
# WMS 11631

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramonamagadan18 — CHANGES_REQUESTED** [review]
Hi @bhenndricks ! 

In the Acknowledgment section at Last Updated By/Date, please also add your name.

The compartment name is visible in:

- ai-vector-search-apex-adb/download/images/createadw1.png
- ai-vector-search-apex-adb/download/images/createadw2.png
- ai-vector-search-apex-adb/download/images/image.png
- ai-vector-search-apex-adb/download/images/provision-atp-3.png
- ai-vector-search-apex-adb/download/images/provision-atp-4.png
- ai-vector-search-apex-adb/download/images/provision-atp-8.png
- ai-vector-search-apex-adb/download/images/wallet-1.png
- ai-vector-search-apex-adb/setup/images/createpolicy.png
- ai-vector-search-apex-adb/tables/images/sqlworksheet.png


These images look like using the old UI for OCI:

- ai-vector-search-apex-adb/download/images/provision-atp-1.png
- ai-vector-search-apex-adb/download/images/provision-atp-2.png
- ai-vector-search-apex-adb/download/images/provision-atp-3.png
- ai-vector-search-apex-adb/download/images/provision-atp-4.png
- ai-vector-search-apex-adb/setup/images/16-create-compartment.png

**Comment by ramonamagadan18** [comment]
Hi @bhenndricks ! Your branch has multiple conflicts; please solve them.

**Review by klazarz — CHANGES_REQUESTED** [review]
please blur tenancy names in screenshots

**Review by bhenndricks — COMMENTED** [review]
Hi I have changed the requested. Thank you!

**Pull request closed without merging**
